"""Generate the KubeJS area spawner, because In Control cannot populate anything by itself.

In Control's rules **gate and dress**; they never create a spawn. `result: "default"` means "let vanilla
decide", so a rule only ever sees a mob something else already tried to place. Two consequences found on
the local server 2026-09-09:

  - density is thin, because vanilla attempts very little on lit or grassy ground by day; and
  - **NATO and RUAF cannot appear at all.** The three Immersive Engineering soldiers have no biome
    modifier anywhere - not in the IE jar, not in the pack - so nothing ever attempts to spawn one and no
    gating rule can ever fire. They arrive through village raids or a spawn egg, and neither happens on
    the east bank.

In Control's own `spawner.json` does spawn, but `SpawnerConditions` has no coordinate and no `area` key,
so a spawner cannot be tied to a site. That leaves a script.

This one places the right **entity type** in the right box and stops there: In Control is still what
dresses it, because `onjoin` fires whichever way the entity got into the world. So there is one kit
table, in `spawn_rules.py`, and this file never repeats it.

Boxes come from `incontrol_areas.py`, so the spawner and the rules cannot drift apart.

    area_spawner.py [--interval TICKS] [--dry-run]

Density is set by two dials: INTERVAL, how often a pass runs, and the per-area ceiling, how many of the
spawner's own kinds may stand within 48 blocks of a player before it stops adding. Both were halved on
2026-09-09 after the first in-game look read as far too busy around Skadowsky.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from incontrol_areas import BOXES  # noqa: E402

OUT = Path(r"G:/GSCraft/server/kubejs/server_scripts/gscraft_area_spawner.js")

NATO = ["plant", "out_e1", "out_e2", "front_en", "front_es", "sk_out_e"]
RUAF = ["town", "out_w1", "out_w2", "front_wn", "front_ws", "sk_out_w"]

SOLDIERS = ["immersiveengineering:commando", "immersiveengineering:commando",
            "immersiveengineering:commando", "immersiveengineering:fusilier",
            "immersiveengineering:bulwark", "minecraft:pillager", "minecraft:pillager"]
DEAD = ["minecraft:zombie", "minecraft:zombie", "minecraft:zombie",
        "minecraft:husk", "minecraft:zombie_villager"]
# people, not illager casters: a raider, an axeman and a gunman (owner's ruling on tone, 2026-09-09)
SCAV = ["minecraft:pillager", "minecraft:pillager", "minecraft:vindicator",
        "dragonrise_reforge:terrorist"]

# area -> (entity pool, how many of that kind may stand within RADIUS of a player there)
JOBS = {}
for a in NATO + RUAF:
    JOBS[a] = (SOLDIERS, 5)
for a in ("woods",):
    JOBS[a] = (SCAV, 5)

# The Dead are the floor and go everywhere. The Scavengers hold the roads and the ground between
# things, so they ride along in the open areas too - without that they existed only in the Woods, and a
# player in Skadowsky met nothing but zombies.
for a in ("skad", "sk_hosp", "sk_town", "sk_south", "town", "tw_stad", "tw_centre", "tw_slabs",
          "tw_blocks", "plant", "pl_react", "pl_turb", "pl_admin", "pl_switch", "farm", "woods"):
    pool, capn = JOBS.get(a, (None, 0))
    JOBS[a] = ((pool or []) + DEAD, max(capn, 4) + 2)
# In an army's own area a pillager is dressed as that army's Grenadier - In Control dresses by type and
# place, and the kits come first - so a Scavenger pillager placed in the town stood up as RUAF. The live
# tally read 10 RUAF Grenadiers in 30 at the town centre. There the Scavengers are the axeman and the
# gunman only.
SCAV_NOT_PILLAGER = [m for m in SCAV if m != "minecraft:pillager"]
for a in ("skad", "sk_town", "sk_south", "town", "tw_blocks", "farm"):
    extra = SCAV_NOT_PILLAGER if a in NATO + RUAF else SCAV
    JOBS[a] = (JOBS[a][0] + extra, JOBS[a][1] + 1)

# And a fallback for ground no box claims - the roads, the fields, the space between sites. Without one
# the spawner did nothing at all outside its boxes, which is most of the map.
ANYWHERE = (DEAD + SCAV, 4)


def js_denies():
    """The build boxes, where In Control denies every hostile."""
    from incontrol_areas import BUILDS
    rows = []
    for name in BUILDS:
        x0, x1, z0, z1, _ = BOXES[name]
        rows.append(f"  {{ n: '{name}', x0: {x0}, x1: {x1}, z0: {z0}, z1: {z1} }}")
    return ",\n".join(rows)


def js_boxes():
    rows = []
    for name, (pool, capn) in JOBS.items():
        x0, x1, z0, z1, _ = BOXES[name]
        pool_js = ", ".join(f"'{e}'" for e in pool)
        rows.append(f"  {{ n: '{name}', x0: {x0}, x1: {x1}, z0: {z0}, z1: {z1}, "
                    f"cap: {capn}, pool: [{pool_js}] }}")
    return ",\n".join(rows)


TEMPLATE = '''// GSCraft - the area spawner. GENERATED by tools/area_spawner.py; edit that, not this.
//
// In Control gates and dresses, it does not populate: `result: "default"` only lets through what
// something else already tried to spawn. On grassy or lit ground by day vanilla tries very little, and
// the three IE soldiers have no biome modifier anywhere, so NATO and RUAF could never appear at all.
// This places the right entity type inside the right box; In Control still dresses it, because onjoin
// fires however the entity reached the world. The kit table stays in spawn_rules.py and is not repeated.
//
// Cost control, because this is the first thing here that runs on a timer:
//   - one pass every INTERVAL ticks, not every tick
//   - a pass does nothing at all unless a player is inside one of the boxes
//   - at most ONE mob per player per pass
//   - the local ceiling is counted with a bounded AABB around the player, never a world scan
//   - candidate positions are tried at most TRIES times and abandoned rather than searched for
//
// var, not const, inside handlers: Rhino re-enters the scope and const throws from the first call.

// var, not const, even at the top level. A const declared here reads as undefined from inside a
// function in this Rhino, so MIN_RADIUS + Math.random() * (RADIUS - MIN_RADIUS) came out NaN and every
// candidate position failed its bounds test silently. Same trap as the const-in-handler one.
var INTERVAL = {interval};        // ticks between passes
var RADIUS = 44;                  // how far out a mob may be placed
var MIN_RADIUS = 20;              // and how close it may come
var TRIES = 6;                    // candidate positions per attempt
var COUNT_BOX = 48;               // horizontal half-extent of the AABB used to count what is there
var COUNT_Y = 10;                 // and the vertical one. Kept tight on purpose: at y +/-40 the box
                                  // reached into the caves below and their zombies filled the ceiling,
                                  // so the surface stayed empty while the log read near=32/8.
// `Math` here is java.lang.Math: the static methods resolve (random, cos, floor all work) but the PI
// *field* does not - Math.PI reads undefined, so `Math.random() * Math.PI * 2` was NaN and every
// candidate position failed its bounds test in silence. Write the turn out in full.
var TAU = 6.283185307179586;
var DEBUG = true;                 // logs one line per pass per player; turn off once tuned

// the pool used where no box claims the ground: the roads and the open country between sites
var ANYWHERE = {{ n: '(open ground)', cap: {any_cap}, pool: [{any_pool}] }};

// The builds, where In Control denies every hostile. The spawner has to know them too: without this it
// placed happily inside the camp and In Control deleted each mob as it joined, so the log read
// "placed=true near=0" for ever while the player saw nothing.
var DENIES = [
{denies}
];

function inDeny(x, z) {{
  for (var i = 0; i < DENIES.length; i++) {{
    var d = DENIES[i];
    if (x >= d.x0 && x <= d.x1 && z >= d.z0 && z <= d.z1) return true;
  }}
  return false;
}}

var AREAS = [
{boxes}
];

// the entity kinds the spawner places, plus the hostiles vanilla puts in the same ground: these are
// what the local ceiling counts, and nothing else
var OURS = ['zombie', 'husk', 'drowned', 'pillager', 'vindicator', 'terrorist', 'commando',
            'fusilier', 'bulwark', 'skeleton', 'stray', 'spider', 'creeper', 'enderman',
            'pomkotsmechs'];

function isOurs(t) {{
  for (var i = 0; i < OURS.length; i++) {{
    if (t.indexOf(OURS[i]) >= 0) return true;
  }}
  return false;
}}

function areaAt(x, z) {{
  for (var i = 0; i < AREAS.length; i++) {{
    var a = AREAS[i];
    if (x >= a.x0 && x <= a.x1 && z >= a.z0 && z <= a.z1) return a;
  }}
  return null;
}}

function surfaceY(level, x, z) {{
  // the debug driver has no player to take an elevation from, so find the ground
  for (var y = 200; y > -60; y--) {{
    if (level.getBlock(x, y, z).id !== 'minecraft:air') return y + 1;
  }}
  return 80;
}}

var gsDiag = {{ outside: 0, noground: 0, nocreate: 0, placed: 0, tries: 0 }};

function tryPlace(level, px, py, pz, area) {{
  // Coerce first. A Java Integer in a `+` with a JS double makes Rhino concatenate strings, so
  // Math.floor("400" + 12.3) is NaN and every bounds test then fails silently.
  px = Number(px); py = Number(py); pz = Number(pz);
  for (var t = 0; t < TRIES; t++) {{
    gsDiag.tries++;
    var ang = Math.random() * TAU;
    var dist = MIN_RADIUS + Math.random() * (RADIUS - MIN_RADIUS);
    var x = Math.floor(px + Math.cos(ang) * dist);
    var z = Math.floor(pz + Math.sin(ang) * dist);
    // stay inside the box that asked for it; the open-ground pool has no box to stay inside
    if (inDeny(x, z)) {{ gsDiag.outside++; continue; }}
    if (area.x0 !== undefined && !areaAt(x, z)) {{ gsDiag.outside++; continue; }}
    var found = false;
    for (var dy = 10; dy >= -24; dy--) {{      // wide enough for a player on a roof or in a cellar
      var y = py + dy;
      var below = level.getBlock(x, y - 1, z);
      if (below.id === 'minecraft:air' || below.id === 'minecraft:water') continue;
      if (level.getBlock(x, y, z).id !== 'minecraft:air') continue;
      if (level.getBlock(x, y + 1, z).id !== 'minecraft:air') continue;
      var pool = area.pool;
      var id = pool[Math.floor(Math.random() * pool.length)];
      var e = level.createEntity(id);
      if (!e) {{ gsDiag.nocreate++; return false; }}
      e.setPosition(x + 0.5, y, z + 0.5);
      // Tag before spawn(), so the tag already exists when In Control's onjoin rule evaluates it. That
      // tag is how In Control tells a mob this spawner placed from one vanilla spawned by itself: the
      // placed ones are let through, and the Dead that vanilla adds on its own are refused, which leaves
      // this spawner's local ceiling as the one thing deciding how thick the ground is.
      e.addTag('gs_placed');
      e.spawn();
      gsDiag.placed++;
      return true;
    }}
    if (!found) gsDiag.noground++;
  }}
  return false;
}}

function tryPlaceMan(level, px, py, pz, area) {{
  var near = level.getEntitiesWithin(
    AABB.of(px - 96, py - 32, pz - 96, px + 96, py + 32, pz + 96));
  for (var i = 0; i < near.length; i++) {{
    if (String(near[i].type).indexOf('man:') >= 0) return;   // only ever one of him
  }}
  var saved = area.pool;
  area.pool = ['man:manfromthefog'];
  tryPlace(level, px, py, pz, area);
  area.pool = saved;
}}

var gscraftTick = 0;

ServerEvents.tick(event => {{
  try {{
    gscraftTick++;
    if (gscraftTick % INTERVAL !== 0) return;
    var players = event.server.getPlayers();
    if (!players || players.length === 0) return;      // nobody about: cost nothing
    for (var i = 0; i < players.length; i++) {{
      var p = players[i];
      var area = areaAt(Math.floor(p.x), Math.floor(p.z)) || ANYWHERE;
      var inSafe = inDeny(Math.floor(p.x), Math.floor(p.z));
      var level = p.level;
      var near = level.getEntitiesWithin(
        AABB.of(p.x - COUNT_BOX, p.y - COUNT_Y, p.z - COUNT_BOX,
                p.x + COUNT_BOX, p.y + COUNT_Y, p.z + COUNT_BOX));
      // Count only what this spawner is responsible for. Counting every entity meant villagers,
      // animals, item frames and boats filled the ceiling before a single mob was placed - the log read
      // "near=14/10 placed=false" in a town square with no hostiles in sight.
      var n = 0;
      for (var k = 0; k < near.length; k++) {{
        if (isOurs(String(near[k].type))) n++;
      }}
      // The fog man is location-based now, not a global timer. The mod's own enable_spawning fired
      // every 4 to 16 minutes anywhere on the map, day included, and once produced the sound and the
      // visuals with no man behind them - which is what disconnected the owner. He belongs to the
      // Woods (entities-v8 s167: "his only land by day"), rarely, and after dark.
      if (area.n === 'woods' && Math.random() < 0.02 && level.getDayTime() % 24000 > 13000) {{
        tryPlaceMan(level, Math.floor(p.x), Math.floor(p.y), Math.floor(p.z), area);
      }}
      var placed = (n < area.cap)
        && tryPlace(level, Math.floor(p.x), Math.floor(p.y), Math.floor(p.z), area);
      if (DEBUG) {{
        console.info('[gscraft][spawn] ' + p.username + ' in ' + area.n + ' near=' + n
                     + '/' + area.cap + ' placed=' + placed
                     + (inSafe ? ' (standing in a no-spawn build)' : ''));
      }}
    }}
  }} catch (err) {{
    console.error('[gscraft] area spawner failed: ' + err);
  }}
}});

// A debug driver, so the spawner can be exercised and timed without a player standing in the box.
//   /gscraftspawn <x> <z> <passes>
// It runs the same placement the tick pass runs, at that point, and reports how long it took.
ServerEvents.commandRegistry(event => {{
  var Commands = event.commands;
  var Arguments = event.arguments;
  event.register(
    Commands.literal('gscraftspawn')
      .requires(src => src.hasPermission(2))
      .then(Commands.argument('x', Arguments.INTEGER.create(event))
        .then(Commands.argument('z', Arguments.INTEGER.create(event))
          .then(Commands.argument('passes', Arguments.INTEGER.create(event))
            .executes(ctx => {{
              try {{
                var x = Number(Arguments.INTEGER.getResult(ctx, 'x'));
                var z = Number(Arguments.INTEGER.getResult(ctx, 'z'));
                var passes = Number(Arguments.INTEGER.getResult(ctx, 'passes'));
                var area = areaAt(x, z);
                if (!area) {{
                  ctx.source.sendSystemMessage(Text.of('no area at ' + x + ',' + z));
                  return 0;
                }}
                var level = ctx.source.getLevel();
                var y = surfaceY(level, x, z);
                gsDiag = {{ outside: 0, noground: 0, nocreate: 0, placed: 0, tries: 0 }};
                var t0 = Date.now();
                var placed = 0;
                for (var i = 0; i < passes; i++) {{
                  if (tryPlace(level, x, y, z, area)) placed++;
                }}
                var ms = Date.now() - t0;
                ctx.source.sendSystemMessage(Text.of(
                  'area ' + area.n + ' at y' + y + ': ' + placed + '/' + passes + ' in ' + ms + ' ms ('
                  + (ms / Math.max(passes, 1)).toFixed(2) + ' ms/pass) tries=' + gsDiag.tries
                  + ' outside=' + gsDiag.outside + ' noground=' + gsDiag.noground
                  + ' nocreate=' + gsDiag.nocreate));
                return placed;
              }} catch (err) {{
                ctx.source.sendSystemMessage(Text.of('spawner debug failed: ' + err));
                return 0;
              }}
            }})))));
}});

console.info('[gscraft] area spawner armed: ' + AREAS.length + ' areas, one pass every '
             + INTERVAL + ' ticks');
'''


def main(argv):
    interval = 200
    if "--interval" in argv:
        interval = int(argv[argv.index("--interval") + 1])
    js = TEMPLATE.format(interval=interval, boxes=js_boxes(),
                         any_cap=ANYWHERE[1],
                         any_pool=", ".join(f"'{e}'" for e in ANYWHERE[0]),
                         denies=js_denies())
    print(f"{len(JOBS)} areas, interval {interval} ticks")
    for name, (pool, capn) in sorted(JOBS.items()):
        kinds = sorted({e.split(":")[-1] for e in pool})
        print(f"   {name:10s} cap {capn:2d}  {', '.join(kinds)}")
    if "--dry-run" in argv:
        print("DRY RUN, nothing written")
        return 0
    OUT.write_text(js, encoding="utf-8", newline="")
    print(f"written to {OUT}")
    return 0


if __name__ == "__main__":
    if "--retired-ok" not in __import__("sys").argv:
        raise SystemExit("RETIRED 2026-09-09: the enemy system lives in mod/ (GSCraft War). This tool rewrites the "
                         "local server's In Control / KubeJS spawn files. Pass --retired-ok to run it anyway.")
    sys.exit(main(sys.argv))
