#!/usr/bin/env python3
"""No other mod puts loot into a chest (loot design 2026-09-19). Forge's global loot modifiers let a mod add to ANY table
as it is rolled, after tools the design controls: Farmer's Delight rolls its own fd_* tables into vanilla chests, Sophisticated
Backpacks injects backpacks, Superb Warfare injects guns and blueprints (the design's first rule: no table drops a working
gun). LootRemap cannot see them - they act on the rolled list, not on the table.

    python glm.py <server dir>   -> build/datapacks/gscraft/data/forge/loot_modifiers/global_loot_modifiers.json with
                                    "replace": true: every modifier every installed mod registers, EXCEPT those whose own
                                    file names a chest table. Read from the jars in <server dir>/mods. Prints both lists.

The datapack outranks the mods' data, so its list is THE list. A modifier that does not touch chests (a knife's straw, an
affix, a smelting tool) is kept exactly as its mod wrote it. Run again whenever a mod is added or updated.
"""
import json
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "build/datapacks/gscraft/data/forge/loot_modifiers/global_loot_modifiers.json"


# these add to chests too, by a pattern in code or config rather than a table id in their file: TACZ's injector puts guns and
# ammunition into loot, Apotheosis puts affixed gear and gems into any chest
ALSO = {"tacz:loot_table_injector", "apotheosis:affix_loot", "apotheosis:gems"}


def main(argv):
    if len(argv) < 2:
        sys.exit(__doc__)
    keep, drop = [], []
    for jar in sorted((Path(argv[1]) / "mods").glob("*.jar")):
        try:
            z = zipfile.ZipFile(jar)
        except zipfile.BadZipFile:
            continue
        names = set(z.namelist())
        if "data/forge/loot_modifiers/global_loot_modifiers.json" not in names:
            continue
        try:
            entries = json.loads(z.read("data/forge/loot_modifiers/global_loot_modifiers.json").decode("utf-8", "replace")).get("entries", [])
        except json.JSONDecodeError:
            continue
        for e in entries:
            ns, path = e.split(":", 1)
            f = f"data/{ns}/loot_modifiers/{path}.json"
            text = z.read(f).decode("utf-8", "replace") if f in names else ""
            (drop if ":chests/" in text or "chests/" in path or e in ALSO else keep).append((e, jar.name))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({"replace": True, "__comment": "generated by tools/glm.py: every installed modifier except the ones that add to chests", "entries": sorted({e for e, _ in keep})}, indent=1) + "\n", encoding="utf-8")
    print(f"kept {len(keep)}:")
    for e, j in keep:
        print(f"   {e:60} {j}")
    print(f"dropped {len(drop)} (they add loot to chests):")
    for e, j in drop:
        print(f"   {e:60} {j}")
    print("written", OUT)


if __name__ == "__main__":
    main(sys.argv)
