"""RUN BY THE OWNER, OR ON THE OWNER'S WORD NAMING LIVE - never otherwise (HANDOFF: live needs an explicit word).
    cd tools && MSYS_NO_PATHCONV=1 PYTHONIOENCODING=utf-8 python live_deploy.py [--dry]

THE FULL DEPLOY TO LIVE (owner, 2026-09-19: "push to live so the only thing left for me to do is placing the npcs").
Everything built locally since live's last push: the jar, the quest book, the slice datapack (functions + the loot-modifier
list), then by console the leftovers cleared (board, mortar, the south compound's chests, the signs) and the containers
bound. Empty is confirmed by the console's `list` before anything and again before the stop. No region file is uploaded.
Panel calls through tools/bisectpanel.py; the token is never read here."""
import hashlib
import json
import re
import subprocess
import sys
import time
from pathlib import Path

REPO = Path("G:/GSCraft/repo")
TOOLS = REPO / "tools"
JAR = REPO / "mod/build/libs/gscraft-0.1.0.jar"
QUESTS = Path("G:/GSCraft/server/config/ftbquests/quests")
FN = REPO / "build/datapacks/gscraft/data/gscraft/functions"
GLM = REPO / "build/datapacks/gscraft/data/forge/loot_modifiers/global_loot_modifiers.json"
PULL = TOOLS / "pull"
SLICE = "/wasteland-v8/datapacks/gscraft_slice/data"
STAGE = REPO / "build/live_stage"   # generated; not committed
sys.path.insert(0, str(TOOLS))
import chests as CH  # noqa: E402


def panel(*args, t=600):
    r = subprocess.run([sys.executable, str(TOOLS / "bisectpanel.py"), *args], cwd=str(TOOLS), capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=t)
    return (r.stdout + r.stderr).strip()


def log_lines():
    panel("get", "/logs/latest.log")
    p = PULL / "latest.log"
    return p.read_text(encoding="utf-8", errors="replace").splitlines() if p.exists() else []


def state():
    m = re.search(r"state\s+(\w+)", panel("resources"))
    return m.group(1) if m else "?"


def empty():
    panel("cmd", "list")
    time.sleep(5)
    lines = [l for l in log_lines() if "players online" in l]
    return bool(lines) and "There are 0 of" in lines[-1], (lines[-1][lines[-1].find("]: ") + 3:] if lines else "no list line")


def console(cmd, wait=3):
    panel("cmd", cmd)
    time.sleep(wait)


# ---- the three generated functions: load the chunks, bind the containers, let the chunks go
record = json.loads((TOOLS / "chests.json").read_text(encoding="utf-8"))
signs = [l.split()[3:6] for l in (FN / "camp_signs_clear.mcfunction").read_text(encoding="utf-8").splitlines() if l.startswith("execute")]
old = [l.split()[3:6] for l in (FN / "old_compound_chests_clear.mcfunction").read_text(encoding="utf-8").splitlines() if l.startswith("execute")]
ledger = json.loads((TOOLS / "chests_placed.json").read_text(encoding="utf-8"))   # every position the tool ever placed a container at
chunks = sorted({(e["x"] >> 4, e["z"] >> 4) for e in record} | {(int(x) >> 4, int(z) >> 4) for x, _, z in signs + old} | {(x >> 4, z >> 4) for x, _, z in ledger})
# the ORNATE CHESTS out (owner, 2026-09-20: "something that isn't an ornate box"): a placed container is a barrel now, in new places.
# Wherever the ledger says one was placed and a Lootr CHEST still stands, it goes; the new barrels' own spots hold air or a barrel, so they are untouched.
unplace = ["# generated by the deploy: the tool's old placed chests removed (guarded: only where a Lootr chest stands at a ledger position)"]
unplace += [f"execute if block {x} {y} {z} lootr:lootr_chest run setblock {x} {y} {z} minecraft:air" for x, y, z in ledger]
bind = ["# generated by the deploy of 2026-09-19 from tools/chests.json. GUARDED: a placed chest goes only into AIR, a map's own barrel or",
        "# chest is bound only while it is a vanilla container holding NOTHING. A spot live has differently is left alone."]
for e in record:
    p, t = f"{e['x']} {e['y']} {e['z']}", CH.table_id(e["table"])
    if "lootr_barrel" in e["command"] or e["was"] == "minecraft:barrel":
        bind.append(f'execute if block {p} minecraft:barrel{{Items:[]}} run setblock {p} lootr:lootr_barrel{{LootTable:"{t}"}}')
    else:
        bind.append(f'execute if block {p} minecraft:air run setblock {p} lootr:lootr_chest{{LootTable:"{t}"}}')
        bind.append(f'execute if block {p} minecraft:chest{{Items:[]}} run setblock {p} lootr:lootr_chest{{LootTable:"{t}"}}')
    if (e["x"], e["y"], e["z"]) in {tuple(k) for k in ledger}:
        bind[-1 if "lootr_barrel" in e["command"] else -2] = f'execute if block {p} minecraft:air run setblock {p} lootr:lootr_barrel[facing=up]{{LootTable:"{t}"}}'   # one the tool places: a barrel, into air only
STAGE.mkdir(parents=True, exist_ok=True)
for f in STAGE.glob("*"):
    f.unlink()
(STAGE / "deploy_load.mcfunction").write_text("\n".join(f"forceload add {cx * 16} {cz * 16}" for cx, cz in chunks) + "\n", encoding="utf-8", newline="\n")
(STAGE / "deploy_unload.mcfunction").write_text("\n".join(f"forceload remove {cx * 16} {cz * 16}" for cx, cz in chunks) + "\n", encoding="utf-8", newline="\n")
(STAGE / "loot_unplace.mcfunction").write_text("\n".join(unplace) + "\n", encoding="utf-8", newline="\n")
(STAGE / "loot_bind.mcfunction").write_text("\n".join(bind) + "\n", encoding="utf-8", newline="\n")
for f in FN.glob("*.mcfunction"):
    (STAGE / f.name).write_bytes(f.read_bytes())
print(f"staged {len(list(STAGE.glob('*')))} functions; {len(record)} containers in {len(chunks)} chunks; jar {JAR.stat().st_size} sha256 {hashlib.sha256(JAR.read_bytes()).hexdigest()[:8]}")
if "--dry" in sys.argv:
    raise SystemExit("dry run: nothing sent")

ok, who = empty()
print("live:", who)
if not ok:
    raise SystemExit("not empty - stopping here, nothing changed")

# ---- while running: the datapack and the book
print(panel("putdir", str(STAGE), f"{SLICE}/gscraft/functions").splitlines()[-1])
print(panel("mkdir", f"{SLICE}/forge"), "|", panel("mkdir", f"{SLICE}/forge/loot_modifiers"))
print(panel("put", str(GLM), f"{SLICE}/forge/loot_modifiers"))
print(panel("put", str(QUESTS / "data.snbt"), "/config/ftbquests/quests"))
print(panel("put", str(QUESTS / "chapter_groups.snbt"), "/config/ftbquests/quests"))
print(panel("putdir", str(QUESTS / "chapters"), "/config/ftbquests/quests/chapters").splitlines()[-1])

ok, who = empty()
print("live:", who)
if not ok:
    raise SystemExit("not empty - files are uploaded but the server was NOT restarted")
print(panel("power", "stop"))
for i in range(120):
    time.sleep(2)
    if state() == "offline":
        break
print("state", state(), "after", (i + 1) * 2, "s")
if state() != "offline":
    raise SystemExit("did not stop - nothing else done")
print(panel("put", str(JAR), "/mods"))
old_first = (log_lines() or [""])[0]
print(panel("power", "start"))
t0 = time.time()
done, new = None, []
for i in range(200):
    time.sleep(4)
    new = log_lines()
    if new and new[0] != old_first and any("Done (" in l for l in new) and any("[gscraft] settings" in l for l in new):
        done = [l for l in new if "Done (" in l][-1]
        break
print("boot", f"{time.time() - t0:.0f} s:", done[done.find("]: ") + 3:] if done else "NO DONE")
if not done:
    raise SystemExit("no Done - look at the log; nothing else done")
for l in new:
    if any(k in l for k in ("[gscraft] zones loaded", "[gscraft] station:", "[gscraft] loot remap", "[gscraft] items:", "[gscraft] survivors:")):
        print("   ", l[l.find("[gscraft]"):][:170])
errs = [l for l in new if ("ERROR" in l or "Exception" in l) and "gscraft" in l.lower()]
print("gscraft error lines at boot:", len(errs))
for l in errs[:6]:
    print("    ERR", l[:220])
time.sleep(70)   # the console's level is null for about a minute after Done

# ---- by console: the chunks, the leftovers, the containers
led_set = {tuple(k) for k in ledger}
samples = []
for t in ("sites/hospital", "sites/intake", "sites/turbine", "sites/switchyard", "workshop"):
    e = next((e for e in record if e["table"] == t and (e["x"], e["y"], e["z"]) in led_set), None)
    if e:
        samples.append(e)
console("function gscraft:deploy_load", 12)
for fn in ("board_remove", "yard_mortar_clear", "old_compound_chests_clear", "camp_signs_clear", "loot_unplace", "loot_bind"):
    console(f"function gscraft:{fn}", 6)
for cmd in ("gscraft loot tables", "gscraft upgrades", "gscraft kit", "gscraft kit respawn", "gscraft npc list", "gscraft site hospital", "gscraft items",
            "execute if entity @e[type=superbwarfare:mortar]",
            *[f"execute if block {e['x']} {e['y']} {e['z']} lootr:lootr_barrel" for e in samples],   # one placed barrel per site table, from the record: hard-coded spots went stale (2026-09-21)
            "gscraft upgrades at -830 70 -930"):
    console(cmd, 2)
console("function gscraft:deploy_unload", 6)
time.sleep(4)
tail = log_lines()[-140:]
for l in tail:
    if any(k in l for k in ("Executed", "tables:", "now: station", "glock_17", "guide_book", "survivors' spots", "hospital:", "medicine", "Test passed", "Test failed", "placement", "COPIES", "walker:", "marshall:")):
        print("   ", l[l.find("]: ") + 3:][:230])
print("DEPLOYED")
